matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      sudo: required
      dist: trusty
      osx_image: xcode7
    - os: windows
      sudo: false
      script:
        - choco install -y vcbuildtools --version 2015.4 --force 
language: cpp

script:
  - cmake .
  - cmake --build .
